---
- name: install flatpak
  pacman:
    name: flatpak

- name: Add the flathub flatpak repo
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { name: 'flathub', repo: 'https://dl.flathub.org/repo/flathub.flatpakrepo' }
    - { name: 'flathub-beta', repo: 'https://flathub.org/beta-repo/flathub-beta.flatpakrepo' }

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub
  loop:
    - com.spotify.Client
    - com.vscodium.codium
    - com.mojang.Minecraft
    - com.github.Anuken.Mindustry
    - us.zoom.Zoom
    - fi.skyjake.Lagrange # gemini browser
    - net.xmind.XMind # mind mapping
    #- com.microsoft.Teams

- name: Install flatpak beta packages
  community.general.flatpak:
    name: '{{ item }}'
    state: present
    remote: flathub-beta
  loop:
    - org.freecadweb.FreeCAD

#- name: Override Teams perms
#  shell: |
#    flatpak override com.microsoft.Teams \
#      --filesystem=~/desktop:ro \
#      --filesystem=~/img:ro \
#      --filesystem=~/downloads:ro \
#      --filesystem=~/share:ro

- name: zoom screen sharing
  shell : |
    flatpak override --env=XDG_CURRENT_DESKTOP=GNOME us.zoom.Zoom
