---
- name: install containers packages
  pacman:
    name:
      - docker          # high level container runtime
      - docker-compose  # multi-container docker apps
      - podman          # docker alternative without dockerd
      - kubectl         # kubernetes api cli client
      - kubectx         # switch clusters/namespaces
      - kustomize       # yaml templator
      - minikube        # virtualized local kubernetes cluster
      - k9s             # UI to interact with Kubernetes clusters
      - helm            # kubernetes package manager
      - packer          # golden images creator
      - terraform       # infrastructure as code
      # https://github.com/kubernetes-sigs/krew

- name: install containers aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - kompose-bin     # docker-compose to manifest convertor
      - k3s-bin         # Lightweight Kubernetes in a signle binary
      - stern           # tail multiple pods on Kubernetes
      - kubespy         # observe Kubernetes resources in real time

- name: install pip3 containers packages
  pip:
    name:
      - podman-compose  # mutli-container podman apps

- name: copy subuid files for podman rootless
  template:
    src: subuid.j2
    dest: /etc/subuid

- name: copy subgid files for podman rootless
  template:
    src: subgid.j2
    dest: /etc/subgid

- name: configure podman registries
  copy:
    src: registries.conf
    dest: /etc/containers/

- name: configure podman storage
  copy:
    src: storage.conf
    dest: /etc/containers/

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
