---
- name: install containers packages
  pacman:
    name:
      - docker
      - docker-compose
      - podman
      - kubectl
      - kubectx
      - minikube
  notify: restart docker

- name: copy subuid files
  template:
    src: subuid.j2
    dest: /etc/subuid

- name: copy subgid files
  template:
    src: subgid.j2
    dest: /etc/subgid

- name: Add user to libvirt group
  user:
    name: '{{user}}'
    groups: docker
    append: yes
