---
- hosts: all
  become: yes

  vars:
    user: user
    shell: /usr/bin/fish
    cmdline: "resume=/dev/mapper/swap"

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

  roles:
    - { role: boot, tags: boot }
    - { role: pacman, tags: pacman }
    - { role: aur, tags: aur }
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: snapper, tags: snapper }
    - { role: virtualization, tags: virtualization }
    - { role: containers, tags: containers }
    - { role: recovery, tags: recovery }
